### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by marcolenzo** [xpamcorp/peon#15]
We need to discuss API versioning. Mainly it's a matter of URI vs Accept Header/Hypermedia.

Please come forward with concrete examples.

**Comment by marcolenzo** [comment]
I vote for URIs for the following reasons:

- It's explicit. Version is visible.
- Easy to query for available versions.
- When updating version, especially in a non backward compatible way, you are practically introducing a new service. Hence there's no value in keeping the URI the same. The service has changed.
- Easier to code against an URI than Headers.
- Easier and less expensive to route with most HW and SW methods

In general I don't envisage us going towards the HATEOAS. URI version is widespread especially in similar projects which involve expertise from both SW and SYS perspective. See for reference, AWS and most Google APIs.

URI is mostly understood by non technical guys that know the inside out of being RESTful :)

This is not a fresh article but the guy was basically looking at what the big players do. URI is prominent.

http://www.lexicalscope.com/blog/2012/03/12/how-are-rest-apis-versioned/

**Comment by kurtpa** [comment]
I don't think we need to version APIs at all. At this stage i don't see why we wouldn't have the same version of the UI and the API deployed. As such we only need to support 1 version at any given time - the "latest" version vis the code deployed.

re: URI vs Header, here's a more recent article: http://www.narwhl.com/2015/03/the-ultimate-solution-to-versioning-rest-apis-content-negotiation/  . Another more discussive article here initially offers multiple options but internally goes down the route of not changing th eURL and using the accepts header when necessary. http://www.troyhunt.com/2014/02/your-api-versioning-is-wrong-which-is.html

In summary we're using HTTP - it already has mechanisms to support content negotiation and it only needs to be used when the client cares about the version. No need to couple with URL

HATEOAS is a completely different issue. Since steps in the pipeline are polymorphic and may have different potential states or operations that can be performed on them. It is far cleaner to offer these operations in a hypermedia _links {..} section of the response and couple the UI to each operation individually rather than the entire enclosing type. This will make checking which are possibly completely offloaded from the UI to the API which usually has the data on hand to offer these options without additional calls or checks.

**Comment by marcolenzo** [comment]
I agree that at this stage there is no chance of anyone creating its own UI to interface with our API. However if we manage to get some traction we should consider versioning. Take for instance the case of Mesos and Kubernetes and you will find a large number of third-party UIs built on top of their APIs.

Regarding the URI vs Header, I get your point and I like Hunt's article. I think this is a case where I prefer to break the semantics because I see no huge win with sticking with them.

Same goes for HATEOAS. I think it is a very elegant way to build a client. My feeling is that it is not the easiest approach. I'd rather focus on the UX of my UI and expect the API to be stable rather than coding defensively to automatically adapt to change :)

Anyway we all know how talks about REST are :)

I'll close this issue since we agree we don't need versioning at this stage.

**Comment by kurtparis** [comment]
I think that clients build on hypermedia are actually simpler to build.

Say we have a job that can be started or stopped depending on it's state. In traditional ui's you would have to write conditions like "if job.isRunnable && job.isStarted then show stop button, else if..."

With hypermedia the check becomes "if _links.contains("stop") show stop button". You could of couse go one further and contain more info in the hypermedia section (what parameters to expect etc) however i agree that may add additional complexity to render on the client side
